num = int(input("please give me a number: (base-ten)"))
num2 = int(input("please give me another number: (base-ten)"))
print(f"The first number {num}, expressed in binary, is {num:#b}.")
print(f"The first number {num}, expressed in octal, is {num:#o}.")
print(f"The first number {num}, expressed in hexadecimal, is {num:#x}.")
print(f"The second number {num2}, expressed in binary, is {num2:#b}.")
print(f"The second number {num2}, expressed in octal, is {num2:#o}.")
print(f"The second number {num2}, expressed in hexadecimal, is {num2:#x}.")
print(f"The sum of the 2 numbers expressed in binary, is {num + num2:#b}.")
print(f"The sum of the 2 numbers expressed in octal, is {num + num2:#o}.")
print(f"The sum of the 2 numbers expressed in hexadecimal, is {num + num2:#x}.")